version: "3.1"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web_app_container
        image: web_app_image
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        networks:
            - app-network
        restart: always

networks:
    app-network:
        driver: bridge
